export const UPDATE_EVENT_TITLE = 'UPDATE_EVENT_TITLE';
export const UPDATE_DATE = 'UPDATE_DATE';
export const SET_TIME_START = 'SET_TIME_START';
export const SET_TIME_END = 'SET_TIME_END';
export const SET_ACTIVITY_TYPE = 'SET_ACTIVITY_TYPE';
export const SET_NUM_PARTICIPANTS = 'SET_NUM_PARTICIPANTS';
export const SET_LOCATION = 'SET_LOCATION';
export const SET_HOST_NAME = 'SET_HOST_NAME';
export const ADD_EVENT = 'ADD_EVENT';
export const SET_DATA = 'SET_DATA';
export const SET_SORT_TYPE = 'SET_SORT_TYPE'



//COMMENT THIS OUT AFTER
export const WHATACTIONAREWEDOING = 'WHATACTIONAREWEDOING'